services:
  db:
    image: postgres:16
    container_name: flightsystem-db
    environment:
      POSTGRES_DB: flight_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tanh@0602
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flightsystem-redis
    ports:
      - "6379:6379"

  backend:
    build: ./API-FlightSystem
    container_name: flightsystem-backend
    ports:
      - "6789:6789"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Urls=http://+:6789
      - Database__Main=Host=db;Port=5432;Database=flight_system_db;Username=postgres;Password=Tanh@0602
      - ConnectionStrings__Redis=redis:6379
      - ServerSetting__CurrentDomain=http://localhost:6789/api/v1
      - ServerSetting__WithOrigins__0=http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./UI-FlightSystem
      args:
        VITE_API_URL: http://localhost:6789/api/v1
        VITE_HUB_URL: http://localhost:6789
    container_name: flightsystem-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pg_data: