export const PATHS = {
    ADMIN: {
        LOGIN: "/admin/login",
        ROOT: "/admin",
        DASHBOARD: "dashboard",
        ACCOUNTS: "accounts",
        SERVICES: "services",
        REVIEWS: "reviews",
        AIRLINES: "airlines",
        AIRPORTS: "airports",
        PLANES: "planes",
        ROUTES: "routes",
        BOOKINGS: "bookings",
        BOOKING_DETAIL: "bookings/:id",
        FLIGHTS: "flights",
        FLIGHT_NEW: "flights/add",
        FLIGHT_EDIT: "flights/edit/:id",
        PROFILE: "profile",
        SUPPORT: "support-requests",
    },
    CLIENT: {
        HOME: "/",
        SEARCH: "/search",
        CONTACT: "/contact",
        HELP: "/help",
        BOOKING: "/booking",
        PAYMENT: "/payment",
        SUCCESS: "/payment/success",
        SEAT_SELECTION: "/seat-selection",
        PROFILE: {
            ROOT: "/profile",
            EDIT: "edit",
            TRANSACTIONS: "transactions",
            REVIEWS: "reviews",
            VERIFY: "verify",
            SUPPORT: "support-requests",
            SUPPORT_CREATE: "support-requests/create",
        },
    },
};